{{- if and .Values.secret.create .Values.secret.railsMasterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager-backend.secretName" . }}
  labels:
    {{- include "task-manager-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  RAILS_MASTER_KEY: {{ .Values.secret.railsMasterKey | quote }}
{{- end }}
