{{- if and .Values.secretsStore.enabled .Values.secretsStore.secretArn .Values.secretsStore.region }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "task-manager-backend.secretProviderClassName" . }}
  labels:
    {{- include "task-manager-backend.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secretsStore.region | quote }}
    objects: |
      - objectName: {{ .Values.secretsStore.secretArn | quote }}
        objectType: "secretsmanager"
        jmesPath:
{{- range .Values.secretsStore.jmesPath }}
          - path: {{ . | quote }}
            objectAlias: {{ . | quote }}
{{- end }}
{{- end }}
