{{- if and .Values.backend.secret.create .Values.backend.secret.railsMasterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.backendSecretName" . }}
  labels:
    {{- include "task-manager.backendLabels" . | nindent 4 }}
type: Opaque
stringData:
  RAILS_MASTER_KEY: {{ .Values.backend.secret.railsMasterKey | quote }}
{{- end }}
