apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-manager.frontendName" . }}
  labels:
    {{- include "task-manager.frontendLabels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "task-manager.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
