imagePullSecrets: []

replicaCount: 1

image:
  repository: ghcr.io/mrh-jishan/task-manager-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations: {}

env:
  RAILS_ENV: production

podAnnotations: {}
podLabels: {}
resources: {}

serviceAccount:
  create: true
  name: task-manager-backend
  annotations: {}

secret:
  create: false
  existingSecret: ""
  railsMasterKey: ""

secretEnv:
  RAILS_MASTER_KEY: RAILS_MASTER_KEY

secretsStore:
  enabled: false
  region: ""
  secretArn: ""
  mountPath: /mnt/secrets-store
  secretProviderClassName: ""
  jmesPath:
    - BACKEND_DATABASE_HOST
    - BACKEND_DATABASE_PORT
    - BACKEND_DATABASE_NAME
    - BACKEND_DATABASE_USERNAME
    - BACKEND_DATABASE_PASSWORD
    - BACKEND_CACHE_DATABASE_NAME
    - BACKEND_QUEUE_DATABASE_NAME
    - BACKEND_CABLE_DATABASE_NAME

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClass: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: api.task-manager.local
  path: /
  pathType: Prefix
  tls: []

livenessProbe:
  path: /up
  initialDelaySeconds: 20
  periodSeconds: 20

readinessProbe:
  path: /up
  initialDelaySeconds: 10
  periodSeconds: 10
